# Generated by Django 2.2.8 on 2020-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
